# Generated by Django 5.2.5 on 2025-09-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FxConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_code', models.CharField(default='BRL', max_length=3, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='rate_brl',
            new_name='rate_per_base',
        ),
    ]
