# Generated by Django 5.2.5 on 2025-09-08 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambio', '0002_fxconfig_rename_rate_brl_rate_rate_per_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_per_base', models.DecimalField(decimal_places=6, max_digits=16)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='cambio.rate')),
            ],
        ),
    ]
